### ISSUE TITLE
虚拟机乌班图19.04 + WIN11 方案无效

### ISSUE THREAD

**Issue by While-Shark** [jklujklu/xbox-switch#1]
![image](https://user-images.githubusercontent.com/24545680/176983195-a704ca9c-a18e-4da6-b985-1d669443dc15.png)

按照教程步骤，启动py脚本后，卡在这不动

ns也没有连接到xbox

**Comment by jklujklu** [comment]
> ![image](https://user-images.githubusercontent.com/24545680/176983195-a704ca9c-a18e-4da6-b985-1d669443dc15.png)
> 
> 按照教程步骤，启动py脚本后，卡在这不动
> 
> ns也没有连接到xbox


这个可能是蓝牙芯片与程序的兼容问题，我自己也试了一下，我的win10 + ubuntu 22 + ax210同样也是无效的
目前可能还没有解决办法

**Comment by While-Shark** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
