### ISSUE TITLE
Amiibo bin只能读取，没法写入

### ISSUE THREAD

**Issue by While-Shark** [jklujklu/xbox-switch#2]
Amiibo bin只能读取，没法写入。。。只能试玩。。

**Comment by jklujklu** [comment]
> Amiibo bin只能读取，没法写入。。。只能试玩。。

我确实比较草率了，现在我正在重构这个代码，增加可扩展性，但最近比较忙，可能时间会慢一点

**Comment by jklujklu** [comment]
目前新版本的已经可以实现自主添加Amiibo，同时修改了部分代码，你有兴趣的话可以尝试下哈

**Comment by While-Shark** [comment]
这个只能读取 不能写入吗。如果不能写入的话，，只能用来刷道具了

**Comment by jklujklu** [comment]
> 这个只能读取 不能写入吗。如果不能写入的话，，只能用来刷道具了

是的，目前只支持刷Amiibo，另外手柄的NFC功能应该也只有Amiibo吧，应该也不需要加载自定义内容

顺带提一下，现在的程序已经支持添加所有游戏的Amiibo

![image](https://user-images.githubusercontent.com/44188259/179437245-3c8aa5cd-b176-4a5b-a9de-4e42d4f19215.png)

如果想要加载除Amiibo以外的自定义内容，可以参照下面的代码

[调用](https://github.com/jklujklu/xbox-switch/blob/master/main.py#L99)

[NFCTag](https://github.com/jklujklu/xbox-switch/blob/48c77ce736847b06b631482605e4b2346971a7f0/joycontrol/nfc_tag.py#L41)

**Comment by While-Shark** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
